apiVersion: thismatters.github/v1alpha
kind: Django
metadata:
  name: example-project
  namespace: example
spec:
  host: app.example.com
  image: registry.example.com/repo/project
  version: "2021.12.1"
  # it is expected that the version will be the tag for the image
  clusterIssuer: letsencrypt
  autoscalers:
    app:
      cpuUtilizationThreshold: 70
      replicas:
        minimum: 1
    worker:
      replicas:
        minimum: 1
        maximum: 2
  resourceRequests:
    app:
      memory: "300Mi"
    beat:
      memory: "100Mi"
    worker:
      memory: "300Mi"
      cpu: "1000m"
  ports:
    app: 8000  # this needs to be exposed by the image
    redis: 6379
  env:
  - name: REGULAR_ENV_VAR
    value: "regular value"
  envFromConfigMapRefs:
  - env
  envFromSecretRefs:
  - database
  imagePullSecrets:
  - name: gitlab-registry-read
  volumes:
  - name: google-drive-client-secret
    secret:
      secretName: google-drive
  volumeMounts:
  - name: google-drive-client-secret
    mountPath: "/app/src/secret/"
    readOnly: true
  alwaysRunMigrations: true
  initManageCommands:
  # these will run in an init pod, migrate might get special treatment vis-a-vi rolling back
  - ["migrate"]
  - ["create_groups"]
  - ["ensure_contract_pricing"]
  - ["initialize_payment_webhooks"]
  - ["loaddata", "money_positive/fixtures/us_states.json"]
  initManageTimeouts:
    period: 6
    iterations: 10
  commands:
    app:
      command:
      - "gunicorn"
      args:
      - "money_positive.wsgi:application"
      - "-b"
      - "0.0.0.0:8000"
    worker:
      command:
      - "celery"
      args:
      - "--app=money_positive"
      - "worker"
      - "--loglevel=INFO"
    beat:
      command:
      - "celery"
      args:
      - "--app=money_positive"
      - "beat"
      - "--loglevel=INFO"
      - "--scheduler"
      - "django_celery_beat.schedulers:DatabaseScheduler"
      - "--pidfile='/tmp/celerybeat.pid'"
  appProbeSpec:
    httpGet:
      scheme: HTTP
      path: /privacy/
      port: 8000
      httpHeaders:
      - name: Host
        value: app.moneypositive.coop
    initialDelaySeconds: 45
    periodSeconds: 11
    timeoutSeconds: 2
    failureThreshold: 3
status:
  version: "2021.12.1"
  condition: "migrating | running | degraded"
  migrationVersion: "2021.12.1"
  replicas:
    app: 3
    worker: 2
  created:
    deployment:
      redis: redis
      beat: beat-2021.12.1
      app: app-2021.12.1
      worker: worker-2021.12.1
    service:
      redis: redis-service
      app: app-service
    ingress:
      app: app-ingress
