apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    role: app
    version: "{version}"
  name: "app-{version_slug}"
  finalizers:
  - "django.thismatters.github/protector"
spec:
  selector:
    matchLabels:
      role: app
  strategy: {{}}
  template:
    metadata:
      labels:
        role: app
        version: "{version}"
    spec:
      imagePullSecrets: []
      volumes: []
      containers:
      - name: app
        image: "{image}"
        envFrom: []
        env:
        - name: CONTAINER_PURPOSE
          value: "{purpose}"
        volumeMounts: []
        ports:
        - containerPort: {app_port}
        livenessProbe: {{}}
        readinessProbe: {{}}
        imagePullPolicy: Always
        resources:
          requests:
            memory: "{app_memory_request}"
            cpu: "{app_cpu_request}"
