apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    role: worker
    version: "{version}"
  name: "worker-{version_slug}"
spec:
  selector:
    matchLabels:
      role: worker
  strategy: {{}}
  template:
    metadata:
      labels:
        role: worker
    spec:
      initContainers:
      - name: init-broker
        image: busybox:1.28.4
        command: ["sh", "-c", "until nslookup redis; do sleep 3; done;"]
      imagePullSecrets: []
      volumes: []
      containers:
      - name: worker
        image: "{image}"
        envFrom: []
        env:
        - name: CONTAINER_PURPOSE
          value: "{purpose}"
        volumeMounts: []
        imagePullPolicy: Always
        resources:
          requests:
            memory: "{worker_memory_request}"
            cpu: "{worker_cpu_request}"
