apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    role: beat
    version: "{version}"
  name: "beat-{version_slug}"
  finalizers:
  - "django.thismatters.github/protector"
spec:
  replicas: 1
  selector:
    matchLabels:
      role: beat
  strategy: {{}}
  template:
    metadata:
      labels:
        role: beat
    spec:
      initContainers:
      - name: init-broker
        image: busybox:1.28.4
        command: ["sh", "-c", "until nslookup redis; do sleep 3; done;"]
      imagePullSecrets: []
      volumes: []
      containers:
      - name: beat
        image: "{image}"
        envFrom: []
        env:
        - name: CONTAINER_PURPOSE
          value: "{purpose}"
        volumeMounts: []
        imagePullPolicy: Always
        resources:
          requests:
            memory: "{beat_memory_request}"
            cpu: "{beat_cpu_request}"
